// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using lender.Core.Persistence;

#nullable disable

namespace lender.Core.Persistence.Migrations
{
    [DbContext(typeof(LenderDbContext))]
    partial class LenderDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("lender")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("lender.Core.Entities.LenderAccessRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<Guid?>("LenderOrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Message")
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Organisation")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Website")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("WorkEmail")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("WorkEmailLookupHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("LenderOrganisationId");

                    b.HasIndex("Status");

                    b.HasIndex("WorkEmailLookupHash");

                    b.ToTable("LenderAccessRequests", "lender");
                });

            modelBuilder.Entity("lender.Core.Entities.LenderInvite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccessRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ConsumedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailLookupHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LenderOrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("AccessRequestId");

                    b.HasIndex("LenderOrganisationId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("LenderInvites", "lender");
                });

            modelBuilder.Entity("lender.Core.Entities.LenderMember", b =>
                {
                    b.Property<Guid>("LenderOrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("LenderOrganisationId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("LenderMembers", "lender");
                });

            modelBuilder.Entity("lender.Core.Entities.LenderOrganisation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Website")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("LenderOrganisations", "lender");
                });

            modelBuilder.Entity("lender.Core.Entities.LenderAccessRequest", b =>
                {
                    b.HasOne("lender.Core.Entities.LenderOrganisation", "LenderOrganisation")
                        .WithMany()
                        .HasForeignKey("LenderOrganisationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LenderOrganisation");
                });

            modelBuilder.Entity("lender.Core.Entities.LenderInvite", b =>
                {
                    b.HasOne("lender.Core.Entities.LenderAccessRequest", "AccessRequest")
                        .WithMany()
                        .HasForeignKey("AccessRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("lender.Core.Entities.LenderOrganisation", "LenderOrganisation")
                        .WithMany("Invites")
                        .HasForeignKey("LenderOrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessRequest");

                    b.Navigation("LenderOrganisation");
                });

            modelBuilder.Entity("lender.Core.Entities.LenderMember", b =>
                {
                    b.HasOne("lender.Core.Entities.LenderOrganisation", "LenderOrganisation")
                        .WithMany("Members")
                        .HasForeignKey("LenderOrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LenderOrganisation");
                });

            modelBuilder.Entity("lender.Core.Entities.LenderOrganisation", b =>
                {
                    b.Navigation("Invites");

                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
