<Project Sdk="Microsoft.NET.Sdk.Web">
  
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>e58049ed-cab6-4f81-b1d4-bc2e2cde0d23</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
    <PackageReference Include="Swashbuckle.AspNetCore.Filters" Version="10.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.0">
    <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
  <ProjectReference Include="..\..\Infrastructure\juskel.Email\juskel.Email.csproj" />
    <ProjectReference Include="..\..\Infrastructure\juskel.Integrations\juskel.Integrations.csproj" />
    <ProjectReference Include="..\..\Shared\juskel.Shared\juskel.Shared.csproj" />
    <ProjectReference Include="..\..\Modules\identity\identity.Contracts\identity.Contracts.csproj" />
    <ProjectReference Include="..\..\Modules\identity\identity.Core\identity.Core.csproj" />
    <ProjectReference Include="..\..\Modules\funding\funding.Contracts\funding.Contracts.csproj" />
    <ProjectReference Include="..\..\Modules\funding\funding.Core\funding.Core.csproj" />
    <ProjectReference Include="..\..\Modules\onboarding\onboarding.Core\onboarding.Core.csproj" />
    <ProjectReference Include="..\..\Modules\onboarding\onboarding.Contracts\onboarding.Contracts.csproj" />
    <ProjectReference Include="..\..\Modules\scoring\scoring.Contracts\scoring.Contracts.csproj" />
    <ProjectReference Include="..\..\Modules\scoring\scoring.Core\scoring.Core.csproj" />
  </ItemGroup>

</Project>
