// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using scoring.Core.Persistence;

#nullable disable

namespace scoring.Core.Migrations
{
    [DbContext(typeof(ScoringDbContext))]
    partial class ScoringDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("scoring")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("scoring.Core.Entities.SustainabilityEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BlobPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("QuestionKey")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId", "QuestionKey");

                    b.ToTable("SustainabilityEvidence", "scoring");
                });

            modelBuilder.Entity("scoring.Core.Entities.SustainabilityProfile", b =>
                {
                    b.Property<Guid>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CarbonFootprint")
                        .HasColumnType("int");

                    b.Property<int>("CommunityEngagement")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeWellbeing")
                        .HasColumnType("int");

                    b.Property<int>("EnergyEfficiency")
                        .HasColumnType("int");

                    b.Property<int>("EnvironmentalCertification")
                        .HasColumnType("int");

                    b.Property<int>("EthicalGovernance")
                        .HasColumnType("int");

                    b.Property<int>("SustainableSourcing")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("WasteReduction")
                        .HasColumnType("int");

                    b.Property<int>("WaterConservation")
                        .HasColumnType("int");

                    b.HasKey("ApplicationId");

                    b.ToTable("SustainabilityProfiles", "scoring");
                });
#pragma warning restore 612, 618
        }
    }
}
